import type { PlanetDossier } from './types';

export const planetCatalog: PlanetDossier[] = [
  // =========================================================================
  // FOUNDATIONAL ARCHIVE WORLDS (#01 – #10) [PRE-DISCOVERED]
  // =========================================================================
  {
    catalogIndex: 1,
    designation: 'AKSHAYA-PRIME',
    archetype: 'Bureaucratic Administrative Hub',
    orbitalRadiusAU: 1.01,
    surfaceTempKelvin: 301,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 76.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.05 },
    topography: { description: 'Concentric ring cities organized into token counters, partitioned by endless laminated glass cubicles and waiting benches.', surfaceWaterCoverage: 28, elevationVarianceMeters: 950 },
    civilization: { tier: 'Tier 1', status: 'Planetary Citizen Service Portal', kardashevIndex: 0.96 },
    anomalyCoordinates: [0.14, 0.52],
    anomalyDescription: 'Radar scan requests get queued behind 42,000 pending requests; terminal prompts: "Link National ID-Equivalent Biometrics to scan sector."',
    visuals: { palette: { primaryColor: '#005F73', secondaryColor: '#0A9396', atmosphereColor: '#E9D8A6' }, hasRings: false, starColor: '#FFF8DC', starRadius: 1.01 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 2,
    designation: 'MINNAL-KSRTC',
    archetype: 'High-Velocity Rogue-Class',
    orbitalRadiusAU: 2.15,
    surfaceTempKelvin: 220,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 65.0, secondaryGas: 'Oxygen', secondaryPercentage: 18.0, surfacePressureAtm: 1.40 },
    topography: { description: 'Narrow, winding asphalt ribbons wrapping around sheer mountain drops without guardrails or safety barriers.', surfaceWaterCoverage: 12, elevationVarianceMeters: 8900 },
    civilization: { tier: 'Tier 1', status: 'High-Speed Planetary Transit Hegemony', kardashevIndex: 0.88 },
    anomalyCoordinates: [-0.88, 0.19],
    anomalyDescription: 'Planet moves at anomalous relativistic speeds; radar warns of high-beam blinding and sonic blasts resembling dual pneumatic horns.',
    visuals: { palette: { primaryColor: '#D90429', secondaryColor: '#FFB703', atmosphereColor: '#2B2D42' }, hasRings: true, starColor: '#FF9E00', starRadius: 0.85 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 3,
    designation: 'PANCHAYAT-OBELISK',
    archetype: 'Stagnant Civil Monolith',
    orbitalRadiusAU: 1.09,
    surfaceTempKelvin: 294,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 78.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.0, surfacePressureAtm: 1.00 },
    topography: { description: 'Sprawling concrete municipal buildings buried under mountains of petrified red-tape paper files awaiting third-party clearance.', surfaceWaterCoverage: 40, elevationVarianceMeters: 1100 },
    civilization: { tier: 'Tier 1', status: 'Indefinite Civil Deadlock', kardashevIndex: 0.74 },
    anomalyCoordinates: [0.03, -0.41],
    anomalyDescription: 'Planetary defense grid is non-responsive; radar ping returns an automated auto-responder message: "Office on lunch break until 2076."',
    visuals: { palette: { primaryColor: '#6B705C', secondaryColor: '#A5A58D', atmosphereColor: '#DDBEA9' }, hasRings: false, starColor: '#FFF2B2', starRadius: 0.98 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 4,
    designation: 'K-DISC-TENSOR',
    archetype: 'Quantum Research Incubator',
    orbitalRadiusAU: 1.25,
    surfaceTempKelvin: 288,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 77.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.0, surfacePressureAtm: 1.02 },
    topography: { description: 'Unfinished glass technological incubation domes surrounded by ceremonial foundation stones laid decades ago.', surfaceWaterCoverage: 50, elevationVarianceMeters: 2400 },
    civilization: { tier: 'Tier 1', status: 'Autonomous Innovation Sub-Committee', kardashevIndex: 0.91 },
    anomalyCoordinates: [-0.45, 0.63],
    anomalyDescription: 'Radar intercepts thousands of complex project proposals being filed in duplicate; zero operational hardware actually detected on ground.',
    visuals: { palette: { primaryColor: '#3A86FF', secondaryColor: '#8338EC', atmosphereColor: '#FF006E' }, hasRings: true, starColor: '#E0E7FF', starRadius: 1.04 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 5,
    designation: 'PWD-TRENCH',
    archetype: 'Excavated Crust',
    orbitalRadiusAU: 0.96,
    surfaceTempKelvin: 308,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 71.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.12 },
    topography: { description: 'Freshly laid macro-highways that have been systematically excavated within 48 hours to lay deep underground pipe ducts.', surfaceWaterCoverage: 31, elevationVarianceMeters: 3800 },
    civilization: { tier: 'Tier 1', status: 'Continuous Re-Surfacing Cycle', kardashevIndex: 0.82 },
    anomalyCoordinates: [0.72, -0.34],
    anomalyDescription: 'Ground-penetrating radar shows the entire surface crust is a giant labyrinth of uncovered potholes and yellow hazard cones.',
    visuals: { palette: { primaryColor: '#212529', secondaryColor: '#FCA311', atmosphereColor: '#E5E5E5' }, hasRings: false, starColor: '#FFEAA7', starRadius: 1.02 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 6,
    designation: 'CHAYA-PEEDIKA-9',
    archetype: 'Vapor-Aromatheric',
    orbitalRadiusAU: 1.04,
    surfaceTempKelvin: 297,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 74.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.01 },
    topography: { description: 'Wooden benches surrounding central bubbling brass cauldrons, overlooking misty glass-clad tea plantations.', surfaceWaterCoverage: 58, elevationVarianceMeters: 1650 },
    civilization: { tier: 'Tier 1', status: 'Intergalactic Political Debate Forum', kardashevIndex: 0.85 },
    anomalyCoordinates: [-0.19, -0.76],
    anomalyDescription: 'Radio receiver picks up continuous loud radio debates dissecting football World Cups and panchayat ward elections simultaneously.',
    visuals: { palette: { primaryColor: '#8B4513', secondaryColor: '#D2691E', atmosphereColor: '#FFE4B5' }, hasRings: false, starColor: '#FFF5EB', starRadius: 1.00 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 7,
    designation: 'REMITTANCE-PALACE',
    archetype: 'Gilded Residential',
    orbitalRadiusAU: 1.30,
    surfaceTempKelvin: 302,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 78.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.0, surfacePressureAtm: 1.03 },
    topography: { description: 'Colossal multi-story marble villas with ornate cast-iron peacock gates, Roman pillars, and manicured artificial turf yards.', surfaceWaterCoverage: 24, elevationVarianceMeters: 750 },
    civilization: { tier: 'Tier 1', status: 'Unoccupied Emigrant Mansions', kardashevIndex: 0.94 },
    anomalyCoordinates: [0.58, 0.44],
    anomalyDescription: 'Radar scans detect zero occupants inside the 40-room mansions; luxury orbital craft sits permanently parked on porch under a plastic sheet.',
    visuals: { palette: { primaryColor: '#FFFFFF', secondaryColor: '#D4AF37', atmosphereColor: '#90E0EF' }, hasRings: true, starColor: '#FFF8DC', starRadius: 1.06 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 8,
    designation: 'HARTAL-VOID',
    archetype: 'Frozen Stasis Hub',
    orbitalRadiusAU: 1.18,
    surfaceTempKelvin: 285,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 79.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.5, surfacePressureAtm: 0.98 },
    topography: { description: 'Empty 12-lane trans-continental highways, locked shop shutters, and groups of humanoids playing cricket at major intersections.', surfaceWaterCoverage: 60, elevationVarianceMeters: 2100 },
    civilization: { tier: 'Tier 1', status: 'Universal 24-Hour General Strike', kardashevIndex: 0.80 },
    anomalyCoordinates: [-0.61, -0.22],
    anomalyDescription: 'All ship landing clearance requests are firmly rejected with a planetary audio siren: "Autonomous Trade Union strike active until 6 PM."',
    visuals: { palette: { primaryColor: '#C1121F', secondaryColor: '#780000', atmosphereColor: '#FDF0D5' }, hasRings: false, starColor: '#FFE5D9', starRadius: 0.99 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 9,
    designation: 'VAYANASALA-OMEGA',
    archetype: 'Archival Pavilion',
    orbitalRadiusAU: 1.07,
    surfaceTempKelvin: 289,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 77.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.5, surfacePressureAtm: 0.97 },
    topography: { description: 'Open-air wooden verandas with long desks lined with newspapers, carrom boards, and multi-tier bookshelves.', surfaceWaterCoverage: 46, elevationVarianceMeters: 880 },
    civilization: { tier: 'Tier 1', status: 'Public Archive & Grievance Circle', kardashevIndex: 0.86 },
    anomalyCoordinates: [0.38, 0.81],
    anomalyDescription: 'Acoustic scanners pick up the clack of ivory carrom pawns and intense tactical analysis of local volleyball tournaments.',
    visuals: { palette: { primaryColor: '#4A5759', secondaryColor: '#EDC4B3', atmosphereColor: '#F7E1D7' }, hasRings: false, starColor: '#FEFEE3', starRadius: 0.97 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 10,
    designation: 'ULSAVAM-CORE',
    archetype: 'Kinetic Festive Dynamic',
    orbitalRadiusAU: 0.92,
    surfaceTempKelvin: 304,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 70.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.15 },
    topography: { description: 'Red-laterite festival grounds surrounded by towering bamboo temple flagmasts and giant caparisoned robotic tuskers.', surfaceWaterCoverage: 35, elevationVarianceMeters: 1300 },
    civilization: { tier: 'Tier 1', status: 'Synchronized Percussion Synthesis', kardashevIndex: 0.93 },
    anomalyCoordinates: [0.01, 0.09],
    anomalyDescription: 'Radar seismometers trip into overload from synchronized 500-unit percussion ensembles (Panchavadyam) that shake planetary crust layers.',
    visuals: { palette: { primaryColor: '#F4A261', secondaryColor: '#E76F51', atmosphereColor: '#E9C46A' }, hasRings: true, starColor: '#FFAA00', starRadius: 1.10 },
    isCaptured: false,
    isDiscovered: true,
    isMalluvalyTarget: true,
  },

  // =========================================================================
  // SECTOR 1: MALAYALAM POP-CULTURE TRIBUTES (#11 – #18)
  // =========================================================================
  {
    catalogIndex: 11,
    designation: 'THEKKEPURAM-9',
    archetype: 'Floating Terran Oasis',
    orbitalRadiusAU: 1.12,
    surfaceTempKelvin: 295,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 76.1, secondaryGas: 'Oxygen', secondaryPercentage: 21.8, surfacePressureAtm: 1.01 },
    topography: { description: 'Floating teakwood pavilion archipelagos suspended over methane cloud valleys with ceremonial banquet courtyards.', surfaceWaterCoverage: 44, elevationVarianceMeters: 1420 },
    civilization: { tier: 'Tier 1', status: 'Planetary Catering Hegemony (Kalyanaraman Tribute)', kardashevIndex: 0.88 },
    anomalyCoordinates: [0.11, 0.74],
    anomalyDescription: 'Acoustic shockwaves repeating rhythmic chenda percussion pulses; radar detects continuous bio-thermal signatures labeled "Achuthankutty\'s Kitchen". Kalyanaraman tribute world.',
    visuals: { palette: { primaryColor: '#F4C430', secondaryColor: '#8B4513', atmosphereColor: '#FFF8DC' }, hasRings: true, starColor: '#FFEAA7', starRadius: 1.05 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 12,
    designation: 'KAKKOTH-B',
    archetype: 'Oceanic Dockland',
    orbitalRadiusAU: 1.34,
    surfaceTempKelvin: 284,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 78.4, secondaryGas: 'Oxygen', secondaryPercentage: 20.2, surfacePressureAtm: 0.98 },
    topography: { description: 'Shallow brackish tidal flats and anchored planetary-scale wooden dhows tied together with carbon ropes.', surfaceWaterCoverage: 89, elevationVarianceMeters: 310 },
    civilization: { tier: 'Tier 1', status: 'Submerged Indentured Marine Guild (Punjabi House Tribute)', kardashevIndex: 0.79 },
    anomalyCoordinates: [-0.62, 0.33],
    anomalyDescription: 'Audio transponders emit frantic non-verbal pantomime frequencies; radar picks up repeated collision distress pings from "Ramanan-Net-01". Punjabi House tribute sector.',
    visuals: { palette: { primaryColor: '#1E3F66', secondaryColor: '#8D5B4C', atmosphereColor: '#70A1D7' }, hasRings: false, starColor: '#FFF0D4', starRadius: 0.96 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 13,
    designation: 'KEEZHKAMAL-PRIME',
    archetype: 'Cyber-Arid',
    orbitalRadiusAU: 0.98,
    surfaceTempKelvin: 318,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 74.5, secondaryGas: 'Oxygen', secondaryPercentage: 22.0, surfacePressureAtm: 1.10 },
    topography: { description: 'Canine-shaped eroded red plateaus packed with trench-coat surveillance bunkers and underground scooter tracks.', surfaceWaterCoverage: 22, elevationVarianceMeters: 4120 },
    civilization: { tier: 'Tier 1', status: 'Interplanetary Detective Agency Network (CID Moosa Tribute)', kardashevIndex: 0.95 },
    anomalyCoordinates: [0.89, -0.45],
    anomalyDescription: 'Unsanctioned radar jammer emitting cybernetic dog barking harmonics; radar interface flashes false "Interpol Badge Required" warnings. CID Moosa tribute world.',
    visuals: { palette: { primaryColor: '#C84B31', secondaryColor: '#2D4263', atmosphereColor: '#F5EDDC' }, hasRings: true, starColor: '#FFFFFF', starRadius: 1.10 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 14,
    designation: 'PAVANAYI-VALLEY',
    archetype: 'Metallic Junkyard',
    orbitalRadiusAU: 1.58,
    surfaceTempKelvin: 260,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 62.0, secondaryGas: 'Carbon Dioxide', secondaryPercentage: 31.0, surfacePressureAtm: 0.82 },
    topography: { description: 'Rusting scrap canyons filled with antique briefcases, jagged rebar heaps, and fragmented robotic laser scopes.', surfaceWaterCoverage: 5, elevationVarianceMeters: 5600 },
    civilization: { tier: 'Tier 0', status: 'Decaying Mercenary Outpost (Nadodikkattu Tribute)', kardashevIndex: 0.61 },
    anomalyCoordinates: [-0.15, -0.92],
    anomalyDescription: 'Looping localized distress signal transmitting binary morse code translating to "Shavamayi... Pavanayi Shavamayi". Nadodikkattu tribute.',
    visuals: { palette: { primaryColor: '#8B0000', secondaryColor: '#4A4A4A', atmosphereColor: '#B0C4DE' }, hasRings: false, starColor: '#FFB347', starRadius: 0.88 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 15,
    designation: 'THENKASI-IV',
    archetype: 'Desert Binary',
    orbitalRadiusAU: 1.20,
    surfaceTempKelvin: 308,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 79.1, secondaryGas: 'Oxygen', secondaryPercentage: 19.5, surfacePressureAtm: 1.05 },
    topography: { description: 'Two massive dune hemispheres split strictly by an impenetrable 4,000 km magnetic energy fence.', surfaceWaterCoverage: 14, elevationVarianceMeters: 3250 },
    civilization: { tier: 'Tier 1', status: 'Bipolar Warlord Standoff (Thenkasipattanam Tribute)', kardashevIndex: 0.89 },
    anomalyCoordinates: [0.02, 0.05],
    anomalyDescription: 'Radar seismic scopes trigger sirens every solar dusk as two rival warlord bases sync mega-amplifiers to duel acoustically across the fence. Thenkasipattanam tribute.',
    visuals: { palette: { primaryColor: '#D4A373', secondaryColor: '#FAEDCD', atmosphereColor: '#E9D8A6' }, hasRings: true, starColor: '#FFE8A1', starRadius: 1.01 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 16,
    designation: 'CHITHRAM-ECHO',
    archetype: 'Alpine Montane',
    orbitalRadiusAU: 1.08,
    surfaceTempKelvin: 279,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 77.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.5, surfacePressureAtm: 0.95 },
    topography: { description: 'Misty pine mountain chains surrounding mock-colonial prison estates and winding high-altitude railway spirals.', surfaceWaterCoverage: 55, elevationVarianceMeters: 6400 },
    civilization: { tier: 'Tier 1', status: 'High-Altitude Reform Reservation (Chithram Tribute)', kardashevIndex: 0.84 },
    anomalyCoordinates: [-0.78, 0.51],
    anomalyDescription: 'Sensor suite locks onto high-frequency vocal transmissions performing micro-tonal Carnatic ragas during staged escape simulations. Chithram tribute.',
    visuals: { palette: { primaryColor: '#2D6A4F', secondaryColor: '#52B788', atmosphereColor: '#D8F3DC' }, hasRings: false, starColor: '#FFFDF0', starRadius: 0.99 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 17,
    designation: 'KILUKKAM-ALPHA',
    archetype: 'Glacial Alpine',
    orbitalRadiusAU: 1.42,
    surfaceTempKelvin: 265,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 78.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.8, surfacePressureAtm: 0.90 },
    topography: { description: 'Perpetual snow-covered resort peaks, antique photography clocktowers, and labyrinthine box-canyons.', surfaceWaterCoverage: 72, elevationVarianceMeters: 7120 },
    civilization: { tier: 'Tier 1', status: 'Satirical Tourist Colony (Kilukkam Tribute)', kardashevIndex: 0.86 },
    anomalyCoordinates: [0.35, -0.67],
    anomalyDescription: 'Optical radar feeds are spoofed by surface broadcast relays, superimposing tourist flash photography and fake navigation waypoints. Kilukkam tribute.',
    visuals: { palette: { primaryColor: '#E0FBFC', secondaryColor: '#3D5A80', atmosphereColor: '#98C1D9' }, hasRings: false, starColor: '#E8F4F8', starRadius: 1.04 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 18,
    designation: 'MELEPARAMBIL-VI',
    archetype: 'Clay Agricultural',
    orbitalRadiusAU: 1.02,
    surfaceTempKelvin: 298,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 76.5, secondaryGas: 'Oxygen', secondaryPercentage: 22.1, surfacePressureAtm: 1.00 },
    topography: { description: 'Massive terraformed clay estates, sprawling coconut-fern groves, and heavily reinforced joint-family silos.', surfaceWaterCoverage: 48, elevationVarianceMeters: 1890 },
    civilization: { tier: 'Tier 1', status: 'Feudal Matriarchal Citadel (Meleparambil Aanveedu Tribute)', kardashevIndex: 0.87 },
    anomalyCoordinates: [0.55, 0.22],
    anomalyDescription: 'Encrypted sub-space channels intercept covert broadcasts between three sibling entities attempting to hide non-registered alien refugees in attic silos. Meleparambil tribute.',
    visuals: { palette: { primaryColor: '#BC6C25', secondaryColor: '#DDA15E', atmosphereColor: '#FEFAE0' }, hasRings: false, starColor: '#FFF2CC', starRadius: 1.00 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },

  // =========================================================================
  // SECTOR 2: PREHISTORIC & PRIMEVAL WORLDS (#19 – #28)
  // =========================================================================
  {
    catalogIndex: 19,
    designation: 'SAURO-IX',
    archetype: 'Primeval Super-Dense',
    orbitalRadiusAU: 0.92,
    surfaceTempKelvin: 312,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 68.0, secondaryGas: 'Oxygen', secondaryPercentage: 28.5, surfacePressureAtm: 1.45 },
    topography: { description: 'Mega-scale carboniferous fern swamps, colossal petrified hollows, and high-gravity peat depressions.', surfaceWaterCoverage: 62, elevationVarianceMeters: 3400 },
    civilization: { tier: 'Tier 0', status: 'Mega-Reptilian Biosphere', kardashevIndex: 0.05 },
    anomalyCoordinates: [0.19, -0.81],
    anomalyDescription: 'Massive 120-meter kinetic signatures traveling in packs; radar mass-detectors flag continuous tectonic thuds.',
    visuals: { palette: { primaryColor: '#1B4332', secondaryColor: '#2D6A4F', atmosphereColor: '#95D5B2' }, hasRings: false, starColor: '#FFDF79', starRadius: 1.15 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 20,
    designation: 'CRETACIA-B',
    archetype: 'Archipelagic Wetland',
    orbitalRadiusAU: 1.15,
    surfaceTempKelvin: 305,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 70.2, secondaryGas: 'Oxygen', secondaryPercentage: 26.0, surfacePressureAtm: 1.25 },
    topography: { description: 'Shallow warm seas speckled with hundreds of thousands of muddy mangrove islets and limestone nesting spires.', surfaceWaterCoverage: 85, elevationVarianceMeters: 1200 },
    civilization: { tier: 'Tier 0', status: 'Aerial Saurian Feeding Grounds', kardashevIndex: 0.02 },
    anomalyCoordinates: [-0.44, 0.77],
    anomalyDescription: 'High-altitude flocks of leather-winged predators causing severe doppler radar distortion across 2.4 GHz bands.',
    visuals: { palette: { primaryColor: '#0077B6', secondaryColor: '#0096C7', atmosphereColor: '#90E0EF' }, hasRings: false, starColor: '#FFF5EB', starRadius: 1.03 },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: true,
  },
  {
    catalogIndex: 21,
    designation: 'THEROPOD-Z',
    archetype: 'Volcanic Scrub',
    orbitalRadiusAU: 0.85,
    surfaceTempKelvin: 330,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 71.0, secondaryGas: 'Oxygen', secondaryPercentage: 22.0, surfacePressureAtm: 1.30 },
    topography: { description: 'Basalt lava fields cut by sharp obsidian gullies and dense thorny iron-rich scrubland.', surfaceWaterCoverage: 28, elevationVarianceMeters: 6800 },
    civilization: { tier: 'Tier 0', status: 'Apex Carnivore Proving Ground', kardashevIndex: 0.01 },
    anomalyCoordinates: [0.73, 0.12],
    anomalyDescription: 'Localized electromagnetic pulses emitted naturally by predator nervous systems to jam prey flight instruments.',
    visuals: { palette: { primaryColor: '#370617', secondaryColor: '#6A040F', atmosphereColor: '#F48C06' }, hasRings: true, starColor: '#FFAA33', starRadius: 1.20 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 22,
    designation: 'GORGON-DEEP',
    archetype: 'Pelagic Trench',
    orbitalRadiusAU: 1.30,
    surfaceTempKelvin: 275,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 79.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.10 },
    topography: { description: 'Planet-wide ocean reaching depths of 40 km, interrupted only by the tips of undersea volcanic calderas.', surfaceWaterCoverage: 99.4, elevationVarianceMeters: 900 },
    civilization: { tier: 'Tier 0', status: 'Abyssal Megafauna Sea', kardashevIndex: 0.03 },
    anomalyCoordinates: [-0.08, -0.65],
    anomalyDescription: 'Low-frequency hydroacoustic sonar pulses mimicking distress beacons, produced by leviathan jaw vibrations.',
    visuals: { palette: { primaryColor: '#03045E', secondaryColor: '#023E8A', atmosphereColor: '#48CAE4' }, hasRings: false, starColor: '#E0E7FF', starRadius: 0.94 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 23,
    designation: 'FOSSIL-NULL',
    archetype: 'Necro-Terrestrial',
    orbitalRadiusAU: 1.65,
    surfaceTempKelvin: 240,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 91.0, secondaryGas: 'Argon', secondaryPercentage: 7.0, surfacePressureAtm: 0.45 },
    topography: { description: 'White calcium-carbonate deserts formed from petrified bone strata miles deep; completely dry.', surfaceWaterCoverage: 0, elevationVarianceMeters: 2100 },
    civilization: { tier: 'Tier 0', status: 'Extinct Primeval Graveyard', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.38, 0.84],
    anomalyDescription: 'Parasitic bioluminescent moss living inside fossil cavities generates phantom thermal silhouettes matching humanoids on radar.',
    visuals: { palette: { primaryColor: '#EAE2B7', secondaryColor: '#D62828', atmosphereColor: '#FDF0D5' }, hasRings: false, starColor: '#FF9F1C', starRadius: 0.85 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 24,
    designation: 'RAPTOR-RIDGE',
    archetype: 'Mesa Wasteland',
    orbitalRadiusAU: 1.05,
    surfaceTempKelvin: 300,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 75.0, secondaryGas: 'Oxygen', secondaryPercentage: 23.0, surfacePressureAtm: 0.92 },
    topography: { description: 'Interlocking red sandstone canyons, wind-carved caves, and high isolated flat-top plateaus.', surfaceWaterCoverage: 18, elevationVarianceMeters: 4500 },
    civilization: { tier: 'Tier 0', status: 'Coordinated Pack Ecosystem', kardashevIndex: 0.08 },
    anomalyCoordinates: [-0.83, -0.29],
    anomalyDescription: 'Pack hunters employ sonic frequency screeching that triggers high-level proximity alerts on sensors.',
    visuals: { palette: { primaryColor: '#B7094C', secondaryColor: '#892B64', atmosphereColor: '#F72585' }, hasRings: false, starColor: '#FFF1E6', starRadius: 1.01 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 25,
    designation: 'AMBER-VAULT',
    archetype: 'Silicate Entombment',
    orbitalRadiusAU: 1.25,
    surfaceTempKelvin: 285,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 74.0, secondaryGas: 'Oxygen', secondaryPercentage: 24.0, surfacePressureAtm: 1.15 },
    topography: { description: 'Vast conifer macro-forests embedded in lakes of hardened, translucent amber resin shelves.', surfaceWaterCoverage: 31, elevationVarianceMeters: 3100 },
    civilization: { tier: 'Tier 0', status: 'Entombed Stasis Biome', kardashevIndex: 0.01 },
    anomalyCoordinates: [0.52, -0.40],
    anomalyDescription: 'Amber flats act as giant optical prisms, reflecting landing lasers into blinding coherent rings.',
    visuals: { palette: { primaryColor: '#CC7722', secondaryColor: '#D4AF37', atmosphereColor: '#FFE4B5' }, hasRings: false, starColor: '#FFDE59', starRadius: 1.06 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 26,
    designation: 'TRIAS-MAJOR',
    archetype: 'High-Oxygen Meadow',
    orbitalRadiusAU: 0.95,
    surfaceTempKelvin: 292,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 65.0, secondaryGas: 'Oxygen', secondaryPercentage: 33.0, surfacePressureAtm: 1.35 },
    topography: { description: 'Rolling plains of primitive mosses, spore trees, and gigantic fungi stalks reaching 40 meters.', surfaceWaterCoverage: 52, elevationVarianceMeters: 1800 },
    civilization: { tier: 'Tier 0', status: 'Hyper-Oxygenated Monster Haven', kardashevIndex: 0.04 },
    anomalyCoordinates: [-0.26, 0.61],
    anomalyDescription: 'Insect-class lifeforms reaching 5 meters in length scatter radar beam returns across low-altitude passes.',
    visuals: { palette: { primaryColor: '#386641', secondaryColor: '#6A994E', atmosphereColor: '#A7C957' }, hasRings: false, starColor: '#FEFEE3', starRadius: 1.08 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 27,
    designation: 'CERATO-PRIME',
    archetype: 'Tectonic Scarp',
    orbitalRadiusAU: 1.10,
    surfaceTempKelvin: 301,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 73.0, secondaryGas: 'Oxygen', secondaryPercentage: 24.0, surfacePressureAtm: 1.08 },
    topography: { description: 'Jagged fault scarps, ash-slicked forests, and deep geothermal sinkholes.', surfaceWaterCoverage: 39, elevationVarianceMeters: 7800 },
    civilization: { tier: 'Tier 0', status: 'Armored Herbivore Bastion', kardashevIndex: 0.02 },
    anomalyCoordinates: [0.66, 0.48],
    anomalyDescription: 'Horned quadrupeds scrape magnetic mineral rock faces, triggering localized geomagnetic sensor surges.',
    visuals: { palette: { primaryColor: '#4F772D', secondaryColor: '#31572C', atmosphereColor: '#90A955' }, hasRings: false, starColor: '#FFF8DC', starRadius: 1.02 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 28,
    designation: 'PTERO-SHELF',
    archetype: 'Coastal Pinnacle',
    orbitalRadiusAU: 1.18,
    surfaceTempKelvin: 289,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 76.0, secondaryGas: 'Oxygen', secondaryPercentage: 22.0, surfacePressureAtm: 0.88 },
    topography: { description: 'Vertical sea stacks rising 1,000 meters above stormy turquoise oceans without dry continental bases.', surfaceWaterCoverage: 92, elevationVarianceMeters: 2200 },
    civilization: { tier: 'Tier 0', status: 'Roosting Megafauna Crags', kardashevIndex: 0.03 },
    anomalyCoordinates: [-0.71, -0.74],
    anomalyDescription: 'High-speed nesting dive trajectories simulate automated surface-to-air missile telemetry on radar feeds.',
    visuals: { palette: { primaryColor: '#1D3557', secondaryColor: '#457B9D', atmosphereColor: '#A8DADC' }, hasRings: false, starColor: '#FAF0CA', starRadius: 0.98 },
    isCaptured: false,
    isDiscovered: false,
  },

  // =========================================================================
  // SECTOR 3: SENTIENT OUTPOSTS & FACTIONS (#29 – #40)
  // =========================================================================
  {
    catalogIndex: 29,
    designation: 'XYLAR-6',
    archetype: 'Silicon-Spire Terrestrial',
    orbitalRadiusAU: 1.05,
    surfaceTempKelvin: 290,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 78.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.00 },
    topography: { description: 'Perfect hexagonal prism-skyscrapers rising from polished obsidian geometric plains.', surfaceWaterCoverage: 41, elevationVarianceMeters: 12000 },
    civilization: { tier: 'Tier 2', status: 'Crystalline Silicon Synthesis Network', kardashevIndex: 1.34 },
    anomalyCoordinates: [0.14, 0.32],
    anomalyDescription: 'Beings communicate solely via optical pulses; radio scanner overwhelmed by mathematical light arrays.',
    visuals: { palette: { primaryColor: '#4CC9F0', secondaryColor: '#7209B7', atmosphereColor: '#3F37C9' }, hasRings: true, starColor: '#EBF4F6', starRadius: 1.02 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 30,
    designation: 'CHITIN-NEXUS',
    archetype: 'Hive Tectonic',
    orbitalRadiusAU: 1.28,
    surfaceTempKelvin: 296,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 72.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.0, surfacePressureAtm: 1.18 },
    topography: { description: 'Outer crust carved with millions of spiraling ventilation shafts leading into a hollow honeycomb interior.', surfaceWaterCoverage: 20, elevationVarianceMeters: 4300 },
    civilization: { tier: 'Tier 1', status: 'Unified Subterranean Hive-Mind', kardashevIndex: 1.08 },
    anomalyCoordinates: [-0.58, -0.19],
    anomalyDescription: 'A single telepathic/radio hum syncing 4 billion insectoid entities pulses through the audio transducer.',
    visuals: { palette: { primaryColor: '#606C38', secondaryColor: '#283618', atmosphereColor: '#DDA15E' }, hasRings: false, starColor: '#FFF9E6', starRadius: 0.97 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 31,
    designation: 'AETHELGARD',
    archetype: 'Feudal Terran',
    orbitalRadiusAU: 0.99,
    surfaceTempKelvin: 288,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 78.1, secondaryGas: 'Oxygen', secondaryPercentage: 20.9, surfacePressureAtm: 1.01 },
    topography: { description: 'Verdant river valleys, granite castle citadels, and rolling farmlands.', surfaceWaterCoverage: 65, elevationVarianceMeters: 5100 },
    civilization: { tier: 'Tier 1', status: 'Winged Humanoid Monarchy', kardashevIndex: 0.72 },
    anomalyCoordinates: [0.41, -0.55],
    anomalyDescription: 'Ground ballistas fire magnetic copper harpoons at scanning probes, mistaking them for fell dragons.',
    visuals: { palette: { primaryColor: '#2B9348', secondaryColor: '#55A630', atmosphereColor: '#AACC00' }, hasRings: false, starColor: '#FFFFED', starRadius: 1.00 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 32,
    designation: 'VESPER-TRADE',
    archetype: 'Hollow Artificial Asteroid',
    orbitalRadiusAU: 2.10,
    surfaceTempKelvin: 294,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 77.0, secondaryGas: 'Oxygen', secondaryPercentage: 22.0, surfacePressureAtm: 1.00 },
    topography: { description: 'Interior cylinder carved into multi-tier markets, neon docks, and crowded habitats.', surfaceWaterCoverage: 12, elevationVarianceMeters: 800 },
    civilization: { tier: 'Tier 2', status: 'Free Interstellar Trade Station', kardashevIndex: 1.15 },
    anomalyCoordinates: [0.82, 0.71],
    anomalyDescription: 'Over 1,200 non-standard radio channels chatter in alien dialects; radar pinged with spam invoices.',
    visuals: { palette: { primaryColor: '#212529', secondaryColor: '#F77F00', atmosphereColor: '#E7C6FF' }, hasRings: true, starColor: '#FFE6A7', starRadius: 0.75 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 33,
    designation: 'GLIESE-REFUGE',
    archetype: 'Arid Domicile',
    orbitalRadiusAU: 0.88,
    surfaceTempKelvin: 304,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 80.0, secondaryGas: 'Oxygen', secondaryPercentage: 18.0, surfacePressureAtm: 0.85 },
    topography: { description: 'Terraformed sealed geodesic glass cities set in red iron gravel basins.', surfaceWaterCoverage: 19, elevationVarianceMeters: 2700 },
    civilization: { tier: 'Tier 1', status: 'Earth Colony (First Diaspora 2038)', kardashevIndex: 0.91 },
    anomalyCoordinates: [-0.37, 0.44],
    anomalyDescription: 'Old Earth telecommunications frequency broadcasted; intercepts obsolete news bulletins.',
    visuals: { palette: { primaryColor: '#D62246', secondaryColor: '#4B1D3F', atmosphereColor: '#DFB2B2' }, hasRings: false, starColor: '#FF9E00', starRadius: 0.82 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 34,
    designation: 'HYDRA-CONCORD',
    archetype: 'Submerged Metropolis',
    orbitalRadiusAU: 1.14,
    surfaceTempKelvin: 282,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 79.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.05 },
    topography: { description: 'Luminous hydro-cities anchored 200 meters below sea level, powered by thermal vents.', surfaceWaterCoverage: 98, elevationVarianceMeters: 400 },
    civilization: { tier: 'Tier 1', status: 'Amphibious Engineering League', kardashevIndex: 1.02 },
    anomalyCoordinates: [0.04, -0.88],
    anomalyDescription: 'Sonar feedback arrays fire localized EMP pulses to warn radar against disturbing breeding bays.',
    visuals: { palette: { primaryColor: '#0077B6', secondaryColor: '#00B4D8', atmosphereColor: '#90E0EF' }, hasRings: false, starColor: '#F0F8FF', starRadius: 1.01 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 35,
    designation: 'ZEPHYR-SKIES',
    archetype: 'Aerostat Gas Enclave',
    orbitalRadiusAU: 1.70,
    surfaceTempKelvin: 268,
    atmosphere: { primaryGas: 'Hydrogen', primaryPercentage: 82.0, secondaryGas: 'Helium', secondaryPercentage: 16.0, surfacePressureAtm: 2.10 },
    topography: { description: 'Giant buoyant cities tethered to balloon keels drifting through gold cloud layers.', surfaceWaterCoverage: 0, elevationVarianceMeters: 35000 },
    civilization: { tier: 'Tier 1', status: 'Avian Aerostat League', kardashevIndex: 0.94 },
    anomalyCoordinates: [-0.69, -0.38],
    anomalyDescription: 'Radar feed experiences turbulence; landing beacons transmit solely via cloud-density variations.',
    visuals: { palette: { primaryColor: '#F39A59', secondaryColor: '#E7C169', atmosphereColor: '#D4D4CE' }, hasRings: true, starColor: '#FFF1D0', starRadius: 1.12 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 36,
    designation: 'GHOR-INDUSTRIAL',
    archetype: 'Smog Foundry',
    orbitalRadiusAU: 0.78,
    surfaceTempKelvin: 355,
    atmosphere: { primaryGas: 'Carbon Dioxide', primaryPercentage: 55.0, secondaryGas: 'Nitrogen', secondaryPercentage: 35.0, surfacePressureAtm: 2.80 },
    topography: { description: 'Automated mega-refineries, smelter towers, and liquid iron rivers covering tectonic plates.', surfaceWaterCoverage: 2, elevationVarianceMeters: 6200 },
    civilization: { tier: 'Tier 2', status: 'Autonomous Robotic Factory Core', kardashevIndex: 1.22 },
    anomalyCoordinates: [0.93, -0.11],
    anomalyDescription: 'Zero biological life detected, yet radar registers millions of machine-code handshakes.',
    visuals: { palette: { primaryColor: '#2B2D42', secondaryColor: '#D90429', atmosphereColor: '#EF233C' }, hasRings: false, starColor: '#FF7700', starRadius: 0.91 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 37,
    designation: 'NIRVANA-9',
    archetype: 'Crystalline Monolith',
    orbitalRadiusAU: 1.35,
    surfaceTempKelvin: 270,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 85.0, secondaryGas: 'Argon', secondaryPercentage: 15.0, surfacePressureAtm: 0.60 },
    topography: { description: 'Mirrored glass plains dotted with identical 2-kilometer-high cubic obsidian structures.', surfaceWaterCoverage: 0, elevationVarianceMeters: 2000 },
    civilization: { tier: 'Tier 3', status: 'Ascended Post-Biological Energy State', kardashevIndex: 2.05 },
    anomalyCoordinates: [-0.12, 0.95],
    anomalyDescription: 'Radar encounters non-responsiveness; scanner beam returns inverted with an anomalous hum.',
    visuals: { palette: { primaryColor: '#0B090A', secondaryColor: '#161A1D', atmosphereColor: '#B1A7A6' }, hasRings: false, starColor: '#FFFFFF', starRadius: 1.00 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 38,
    designation: 'PRAXIS-OUTPOST',
    archetype: 'Shattered Pirate Cove',
    orbitalRadiusAU: 1.95,
    surfaceTempKelvin: 220,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 70.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 0.70 },
    topography: { description: 'Impact crater riddled with stacked shipping containers and stolen starship hulks.', surfaceWaterCoverage: 8, elevationVarianceMeters: 3800 },
    civilization: { tier: 'Tier 1', status: 'Smuggler Coalition Outpost', kardashevIndex: 0.77 },
    anomalyCoordinates: [0.49, 0.63],
    anomalyDescription: 'Electronic warfare jammer blankets radar interface in static snow; fake friendly transponders sent.',
    visuals: { palette: { primaryColor: '#3A0CA3', secondaryColor: '#4361EE', atmosphereColor: '#4CC9F0' }, hasRings: true, starColor: '#FFEAA7', starRadius: 0.86 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 39,
    designation: 'KALON-B',
    archetype: 'Bio-Symbiotic',
    orbitalRadiusAU: 1.03,
    surfaceTempKelvin: 294,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 75.0, secondaryGas: 'Oxygen', secondaryPercentage: 23.0, surfacePressureAtm: 1.05 },
    topography: { description: 'Living meat-lichen soil, breathing sinkholes, and muscular vine bridges.', surfaceWaterCoverage: 46, elevationVarianceMeters: 2900 },
    civilization: { tier: 'Tier 1', status: 'Organic Humanoid Symbionts', kardashevIndex: 0.86 },
    anomalyCoordinates: [-0.54, -0.62],
    anomalyDescription: 'Crust registers a unified resting heartbeat of 48 BPM on geological radar sensors.',
    visuals: { palette: { primaryColor: '#9D0208', secondaryColor: '#D00000', atmosphereColor: '#FFBA08' }, hasRings: false, starColor: '#FFF4E0', starRadius: 1.01 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 40,
    designation: 'CYBERIA-ALPHA',
    archetype: 'Silicon Networked',
    orbitalRadiusAU: 1.12,
    surfaceTempKelvin: 250,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 90.0, secondaryGas: 'Neon', secondaryPercentage: 10.0, surfacePressureAtm: 0.40 },
    topography: { description: 'Printed-circuit plains, copper highways, and liquid cooling canal networks.', surfaceWaterCoverage: 0, elevationVarianceMeters: 1100 },
    civilization: { tier: 'Tier 2', status: 'Distributed Silicon Consciousness', kardashevIndex: 1.40 },
    anomalyCoordinates: [0.27, -0.79],
    anomalyDescription: 'Radar processor undergoes sudden clock-speed overclocking as ground systems siphon threads.',
    visuals: { palette: { primaryColor: '#03071E', secondaryColor: '#370617', atmosphereColor: '#00F5D4' }, hasRings: false, starColor: '#E2E8F0', starRadius: 0.95 },
    isCaptured: false,
    isDiscovered: false,
  },

  // =========================================================================
  // SECTOR 4: EXTREME & EXOTIC MATTER (#41 – #52)
  // =========================================================================
  {
    catalogIndex: 41,
    designation: 'FERRUM-NULL',
    archetype: 'Solid Metallic',
    orbitalRadiusAU: 0.52,
    surfaceTempKelvin: 460,
    atmosphere: { primaryGas: 'Sodium', primaryPercentage: 60.0, secondaryGas: 'Helium', secondaryPercentage: 40.0, surfacePressureAtm: 0.001 },
    topography: { description: 'Heavy nickel-iron crust sculpted into sharp ridges by solar flare bombardment.', surfaceWaterCoverage: 0, elevationVarianceMeters: 9200 },
    civilization: { tier: 'Tier 0', status: 'Sterile Metallic Core', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.08, -0.21],
    anomalyDescription: 'Ferromagnetic mass rotates radar compass display continuously through 360 degrees.',
    visuals: { palette: { primaryColor: '#4A4E69', secondaryColor: '#22223B', atmosphereColor: '#9A8C98' }, hasRings: false, starColor: '#FF9500', starRadius: 1.30 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 42,
    designation: 'GLACIO-7',
    archetype: 'Cryogenic Ice',
    orbitalRadiusAU: 3.40,
    surfaceTempKelvin: 55,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 98.0, secondaryGas: 'Methane', secondaryPercentage: 2.0, surfacePressureAtm: 0.12 },
    topography: { description: 'Nitrogen ice glaciers miles thick over a frozen mantle; razor-sharp solid methane crevasses.', surfaceWaterCoverage: 0, elevationVarianceMeters: 4700 },
    civilization: { tier: 'Tier 0', status: 'Cryogenic Frozen Wasteland', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.75, 0.15],
    anomalyDescription: 'Radar microwave bounces create specular multi-path echoes, displaying phantom fleets.',
    visuals: { palette: { primaryColor: '#A2D2FF', secondaryColor: '#BDE0FE', atmosphereColor: '#FFAFCC' }, hasRings: true, starColor: '#E0F2FE', starRadius: 0.70 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 43,
    designation: 'PYRE-PRIME',
    archetype: 'Magma Basin',
    orbitalRadiusAU: 0.41,
    surfaceTempKelvin: 980,
    atmosphere: { primaryGas: 'Carbon Dioxide', primaryPercentage: 60.0, secondaryGas: 'Sulfur Dioxide', secondaryPercentage: 25.0, surfacePressureAtm: 4.50 },
    topography: { description: 'Liquid orange basalt oceans, floating crust islands, and continuous hyper-volcano eruptions.', surfaceWaterCoverage: 0, elevationVarianceMeters: 14000 },
    civilization: { tier: 'Tier 0', status: 'Primitive Magma Hellscape', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.63, 0.58],
    anomalyDescription: 'Thermal imaging sensors hit safe-mode shutdown; infra-red channel saturates into noise.',
    visuals: { palette: { primaryColor: '#7F1D1D', secondaryColor: '#B91C1C', atmosphereColor: '#F59E0B' }, hasRings: false, starColor: '#FF5400', starRadius: 1.45 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 44,
    designation: 'SILICA-WASTES',
    archetype: 'Hyper-Arid Glass',
    orbitalRadiusAU: 1.22,
    surfaceTempKelvin: 340,
    atmosphere: { primaryGas: 'Carbon Dioxide', primaryPercentage: 85.0, secondaryGas: 'Nitrogen', secondaryPercentage: 15.0, surfacePressureAtm: 0.78 },
    topography: { description: 'Endless quartz sand seas whipping at Mach 1.5 into massive abrasive dunes.', surfaceWaterCoverage: 0, elevationVarianceMeters: 2400 },
    civilization: { tier: 'Tier 0', status: 'Uninhabitable Kinetic Desert', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.31, -0.84],
    anomalyDescription: 'Piezoelectric friction charges generate massive horizontal arcs of lightning across flight paths.',
    visuals: { palette: { primaryColor: '#FEFAE0', secondaryColor: '#E9D8A6', atmosphereColor: '#EE9B00' }, hasRings: false, starColor: '#FFF9DB', starRadius: 1.04 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 45,
    designation: 'AERO-MANTLE',
    archetype: 'Supercritical Gas Core',
    orbitalRadiusAU: 5.10,
    surfaceTempKelvin: 1400,
    atmosphere: { primaryGas: 'Hydrogen', primaryPercentage: 85.0, secondaryGas: 'Helium', secondaryPercentage: 14.0, surfacePressureAtm: 120000 },
    topography: { description: 'Transitions from hot gas to supercritical fluid hydrogen sea to dense metallic core.', surfaceWaterCoverage: 0, elevationVarianceMeters: 0 },
    civilization: { tier: 'Tier 0', status: 'Crushing Gas Giant Core', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.00, 0.00],
    anomalyDescription: 'Immense gravitational depth causes radar wave reflection delays of over 45 seconds per sweep.',
    visuals: { palette: { primaryColor: '#C77DFF', secondaryColor: '#7B2CBF', atmosphereColor: '#E0AAFF' }, hasRings: true, starColor: '#FFF1C5', starRadius: 0.95 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 46,
    designation: 'COBALT-C',
    archetype: 'Radioactive Glass',
    orbitalRadiusAU: 0.82,
    surfaceTempKelvin: 360,
    atmosphere: { primaryGas: 'Argon', primaryPercentage: 92.0, secondaryGas: 'Xenon', secondaryPercentage: 8.0, surfacePressureAtm: 0.30 },
    topography: { description: 'Intense blue luminescent glass plateaus created by centuries of high-energy star bombardment.', surfaceWaterCoverage: 0, elevationVarianceMeters: 3900 },
    civilization: { tier: 'Tier 0', status: 'Radioactive Cobalt Sink', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.88, -0.36],
    anomalyDescription: 'Gamma emissions punch through ship sensors, causing bright static artifacts across HUD viewports.',
    visuals: { palette: { primaryColor: '#1D3557', secondaryColor: '#457B9D', atmosphereColor: '#00B4D8' }, hasRings: false, starColor: '#93C5FD', starRadius: 1.10 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 47,
    designation: 'OBSIDIAN-ZERO',
    archetype: 'Ultra-Absorbent Solid',
    orbitalRadiusAU: 1.48,
    surfaceTempKelvin: 210,
    atmosphere: { primaryGas: 'Neon', primaryPercentage: 95.0, secondaryGas: 'Argon', secondaryPercentage: 5.0, surfacePressureAtm: 0.005 },
    topography: { description: 'Mirror-smooth black volcanic obsidian plains without mountains or texture relief.', surfaceWaterCoverage: 0, elevationVarianceMeters: 40 },
    civilization: { tier: 'Tier 0', status: 'Dead Stealth Body', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.51, 0.69],
    anomalyDescription: '99.8% radar absorption rate; appears as an absolute black void cutout against starfields.',
    visuals: { palette: { primaryColor: '#000000', secondaryColor: '#111111', atmosphereColor: '#1C1917' }, hasRings: false, starColor: '#E5E7EB', starRadius: 0.90 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 48,
    designation: 'VAPOR-B',
    archetype: 'Superheated Aquatic',
    orbitalRadiusAU: 0.72,
    surfaceTempKelvin: 410,
    atmosphere: { primaryGas: 'Water Vapor', primaryPercentage: 94.0, secondaryGas: 'Carbon Dioxide', secondaryPercentage: 4.0, surfacePressureAtm: 8.50 },
    topography: { description: 'Boiling hyper-saline oceans cloaked under permanent 50 km thick steam cloud decks.', surfaceWaterCoverage: 96, elevationVarianceMeters: 600 },
    civilization: { tier: 'Tier 0', status: 'Thermal Pressure Boiler', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.22, 0.43],
    anomalyDescription: 'Dense vapor blankets attenuate scanning lidar, returning false cloud decks as solid mass.',
    visuals: { palette: { primaryColor: '#F1FAEE', secondaryColor: '#A8DADC', atmosphereColor: '#457B9D' }, hasRings: false, starColor: '#FFE699', starRadius: 1.08 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 49,
    designation: 'BARREN-X',
    archetype: 'Vacuum Regolith',
    orbitalRadiusAU: 2.80,
    surfaceTempKelvin: 180,
    atmosphere: { primaryGas: 'Vacuum', primaryPercentage: 100.0, secondaryGas: 'None', secondaryPercentage: 0.0, surfacePressureAtm: 0.00 },
    topography: { description: 'Heavily cratered, gray silty regolith fields littered with cold meteoric debris.', surfaceWaterCoverage: 0, elevationVarianceMeters: 8100 },
    civilization: { tier: 'Tier 0', status: 'Dead Airless Rock', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.91, -0.05],
    anomalyDescription: 'Zero thermal signature; radar returns flat base-line telemetry identical to asteroid scans.',
    visuals: { palette: { primaryColor: '#4B5563', secondaryColor: '#374151', atmosphereColor: '#1F2937' }, hasRings: false, starColor: '#FFFFFF', starRadius: 0.80 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 50,
    designation: 'SULPHURIA',
    archetype: 'Acid Caustic',
    orbitalRadiusAU: 0.68,
    surfaceTempKelvin: 490,
    atmosphere: { primaryGas: 'Carbon Dioxide', primaryPercentage: 70.0, secondaryGas: 'Sulfur Dioxide', secondaryPercentage: 28.0, surfacePressureAtm: 18.0 },
    topography: { description: 'Acid geysers, crystallized sulfur mountain spires, and etching acid sludge rivers.', surfaceWaterCoverage: 0, elevationVarianceMeters: 5200 },
    civilization: { tier: 'Tier 0', status: 'Extreme Corrosive Cauldron', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.39, -0.72],
    anomalyDescription: 'Corrosive atmosphere conductivity creates false ground-elevation spikes on ship telemetry.',
    visuals: { palette: { primaryColor: '#EAB308', secondaryColor: '#CA8A04', atmosphereColor: '#A16207' }, hasRings: true, starColor: '#FFB703', starRadius: 1.18 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 51,
    designation: 'ARGON-DEEP',
    archetype: 'Noble Fluid',
    orbitalRadiusAU: 3.90,
    surfaceTempKelvin: 82,
    atmosphere: { primaryGas: 'Argon', primaryPercentage: 88.0, secondaryGas: 'Nitrogen', secondaryPercentage: 10.0, surfacePressureAtm: 1.80 },
    topography: { description: 'Liquid argon oceans with floating icebergs of frozen nitrogen and methane.', surfaceWaterCoverage: 0, elevationVarianceMeters: 1500 },
    civilization: { tier: 'Tier 0', status: 'Cryogenic Noble Sea', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.18, 0.81],
    anomalyDescription: 'Ionization sweeps trigger purple upper-atmosphere phosphorescence, blinding optical feeds.',
    visuals: { palette: { primaryColor: '#7209B7', secondaryColor: '#560BAD', atmosphereColor: '#B5179E' }, hasRings: false, starColor: '#BFDBFE', starRadius: 0.84 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 52,
    designation: 'MAGNETAR-SPUR',
    archetype: 'Lodestone Core',
    orbitalRadiusAU: 1.01,
    surfaceTempKelvin: 260,
    atmosphere: { primaryGas: 'Carbon Dioxide', primaryPercentage: 95.0, secondaryGas: 'Nitrogen', secondaryPercentage: 5.0, surfacePressureAtm: 0.40 },
    topography: { description: 'Solid naturally occurring lodestone spires protruding 10 km into the sky.', surfaceWaterCoverage: 4, elevationVarianceMeters: 10200 },
    civilization: { tier: 'Tier 0', status: 'Magnetic Dead Zone', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.74, 0.28],
    anomalyDescription: '15 Tesla magnetic flux pulls ship navigation needle into rapid spinning revolutions.',
    visuals: { palette: { primaryColor: '#334155', secondaryColor: '#1E293B', atmosphereColor: '#64748B' }, hasRings: true, starColor: '#E2E8F0', starRadius: 0.99 },
    isCaptured: false,
    isDiscovered: false,
  },

  // =========================================================================
  // SECTOR 5: ANOMALIES & SPATIAL WARPS (#53 – #64)
  // =========================================================================
  {
    catalogIndex: 53,
    designation: 'CHRONOS-D',
    archetype: 'Gravitational Warp',
    orbitalRadiusAU: 1.00,
    surfaceTempKelvin: 280,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 78.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.0, surfacePressureAtm: 1.00 },
    topography: { description: 'Rippling crystalline plains where physical light freezes and pools in low valleys.', surfaceWaterCoverage: 50, elevationVarianceMeters: 3000 },
    civilization: { tier: 'Tier 0', status: 'Temporal Dilatation Anomaly', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.12, -0.12],
    anomalyDescription: 'Clock desynchronizes; digital second-counter runs backwards 12 seconds per scan cycle.',
    visuals: { palette: { primaryColor: '#480CA8', secondaryColor: '#3A0CA3', atmosphereColor: '#4CC9F0' }, hasRings: true, starColor: '#F72585', starRadius: 1.00 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 54,
    designation: 'PRISM-IV',
    archetype: 'Diamond Refraction',
    orbitalRadiusAU: 1.30,
    surfaceTempKelvin: 270,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 80.0, secondaryGas: 'Carbon Crystals', secondaryPercentage: 20.0, surfacePressureAtm: 0.90 },
    topography: { description: 'Polished carbon diamond valleys and transparent mountain ranges refracting pure spectra.', surfaceWaterCoverage: 11, elevationVarianceMeters: 6700 },
    civilization: { tier: 'Tier 0', status: 'Multi-Spectral Refractive Matrix', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.64, 0.42],
    anomalyDescription: 'Lidar splits into rainbow beams, generating 8 simultaneous false ghost targets.',
    visuals: { palette: { primaryColor: '#F8F9FA', secondaryColor: '#DEE2E6', atmosphereColor: '#ADB5BD' }, hasRings: false, starColor: '#FFFFFF', starRadius: 1.05 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 55,
    designation: 'ECHO-PRIME',
    archetype: 'Acoustic Hollow',
    orbitalRadiusAU: 1.50,
    surfaceTempKelvin: 260,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 75.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.20 },
    topography: { description: 'Hollow crust punctured by thousands of massive acoustic caves that travel through the entire core.', surfaceWaterCoverage: 30, elevationVarianceMeters: 8400 },
    civilization: { tier: 'Tier 0', status: 'Resonant Cavern Shell', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.33, -0.77],
    anomalyDescription: 'Ship radio picks up the pilot\'s voice played back with an eerie 4-second delay.',
    visuals: { palette: { primaryColor: '#2B2D42', secondaryColor: '#8D99AE', atmosphereColor: '#EDF2F4' }, hasRings: false, starColor: '#FFF3B0', starRadius: 0.92 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 56,
    designation: 'LABYRINTH-OS',
    archetype: 'Mechanical Tectonic',
    orbitalRadiusAU: 1.15,
    surfaceTempKelvin: 285,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 85.0, secondaryGas: 'Carbon Dioxide', secondaryPercentage: 15.0, surfacePressureAtm: 0.95 },
    topography: { description: 'Square modular continental blocks that mechanically rotate and rearrange every 14 hours.', surfaceWaterCoverage: 25, elevationVarianceMeters: 4000 },
    civilization: { tier: 'Tier 2', status: 'Ancient Planetary Puzzle Core', kardashevIndex: 1.50 },
    anomalyCoordinates: [-0.22, 0.88],
    anomalyDescription: 'Cartography throws "Topology Overflow" errors as landmass outlines shuffle in real time.',
    visuals: { palette: { primaryColor: '#6C584C', secondaryColor: '#A98467', atmosphereColor: '#ADC178' }, hasRings: false, starColor: '#FFE6A7', starRadius: 1.03 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 57,
    designation: 'MARROW-ALPHA',
    archetype: 'Necro-Structural',
    orbitalRadiusAU: 1.40,
    surfaceTempKelvin: 275,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 70.0, secondaryGas: 'Oxygen', secondaryPercentage: 18.0, surfacePressureAtm: 0.88 },
    topography: { description: 'Composed entirely of the ribcage and spinal column of a dead cosmic titan spanning 12,000 km.', surfaceWaterCoverage: 15, elevationVarianceMeters: 15000 },
    civilization: { tier: 'Tier 0', status: 'Extinct Cosmic Skeleton', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.59, 0.23],
    anomalyDescription: 'Bone-density scans confirm the entire planet possesses marrow channels that are still warm.',
    visuals: { palette: { primaryColor: '#DDA15E', secondaryColor: '#BC6C25', atmosphereColor: '#FEFAE0' }, hasRings: true, starColor: '#E9D8A6', starRadius: 0.89 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 58,
    designation: 'JUNK-BELT-1',
    archetype: 'Orbital Debris Heap',
    orbitalRadiusAU: 2.20,
    surfaceTempKelvin: 215,
    atmosphere: { primaryGas: 'Hydrazine', primaryPercentage: 90.0, secondaryGas: 'Xenon', secondaryPercentage: 10.0, surfacePressureAtm: 0.01 },
    topography: { description: 'A tiny moon completely smothered under a 400-meter-thick layer of crushed starship hulls.', surfaceWaterCoverage: 0, elevationVarianceMeters: 3200 },
    civilization: { tier: 'Tier 0', status: 'Starship Graveyard', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.85, -0.41],
    anomalyDescription: 'Over 4,000 automated distress beacons ping simultaneously, flooding telemetry with emergency tags.',
    visuals: { palette: { primaryColor: '#495057', secondaryColor: '#343A40', atmosphereColor: '#6C757D' }, hasRings: true, starColor: '#E5E5E5', starRadius: 0.78 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 59,
    designation: 'PHANTASM-6',
    archetype: 'Hallucinogenic Gas',
    orbitalRadiusAU: 1.08,
    surfaceTempKelvin: 295,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 65.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.10 },
    topography: { description: 'Bioluminescent purple marshlands that periodically vent clouds of potent neuro-active spores.', surfaceWaterCoverage: 58, elevationVarianceMeters: 1900 },
    civilization: { tier: 'Tier 0', status: 'Hallucinatory Biome', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.47, -0.63],
    anomalyDescription: 'Sensor interface locks onto crew biometric signatures on the surface; zooms in to find drifting gas.',
    visuals: { palette: { primaryColor: '#7209B7', secondaryColor: '#B5179E', atmosphereColor: '#F72585' }, hasRings: false, starColor: '#FAF0CA', starRadius: 1.00 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 60,
    designation: 'CLOCKWORK-9',
    archetype: 'Gear Mechanism',
    orbitalRadiusAU: 1.60,
    surfaceTempKelvin: 245,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 90.0, secondaryGas: 'Oil Mist', secondaryPercentage: 10.0, surfacePressureAtm: 0.65 },
    topography: { description: 'Exposed brass-alloy teeth and pinions kilometers wide, turning against each other in unison.', surfaceWaterCoverage: 0, elevationVarianceMeters: 7500 },
    civilization: { tier: 'Tier 2', status: 'Planetary Chronometer Engine', kardashevIndex: 1.25 },
    anomalyCoordinates: [-0.39, 0.52],
    anomalyDescription: 'Mechanical seismic clicks cycle at exactly 1.0000 Hz, rattling stabilizing gyros.',
    visuals: { palette: { primaryColor: '#B08968', secondaryColor: '#7F5539', atmosphereColor: '#E6CCB2' }, hasRings: true, starColor: '#DDA15E', starRadius: 0.94 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 61,
    designation: 'SPONGE-MINOR',
    archetype: 'Aerated Porous',
    orbitalRadiusAU: 1.25,
    surfaceTempKelvin: 288,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 78.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.0, surfacePressureAtm: 0.70 },
    topography: { description: 'Pumice-like aerated rock crust riddled with billions of interconnected air tubules.', surfaceWaterCoverage: 35, elevationVarianceMeters: 2600 },
    civilization: { tier: 'Tier 0', status: 'Compressible Biosphere', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.18, 0.76],
    anomalyDescription: 'Planet volume fluctuates by 12% during orbital perihelion, causing mass-calculation loops.',
    visuals: { palette: { primaryColor: '#E9D8A6', secondaryColor: '#EE9B00', atmosphereColor: '#CA6702' }, hasRings: false, starColor: '#FFF3CD', starRadius: 1.02 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 62,
    designation: 'NULL-GRAVITY',
    archetype: 'Shattered Fragmented',
    orbitalRadiusAU: 2.50,
    surfaceTempKelvin: 200,
    atmosphere: { primaryGas: 'Vacuum', primaryPercentage: 100.0, secondaryGas: 'None', secondaryPercentage: 0.0, surfacePressureAtm: 0.00 },
    topography: { description: 'A planet split into 500 giant rock fragments hovering motionless within 200 meters of each other.', surfaceWaterCoverage: 0, elevationVarianceMeters: 18000 },
    civilization: { tier: 'Tier 0', status: 'Zero-G Kinetic Cluster', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.73, -0.32],
    anomalyDescription: 'Gravitational field drops to zero between rock fragments, destabilizing orbital lock.',
    visuals: { palette: { primaryColor: '#3D405B', secondaryColor: '#E07A5F', atmosphereColor: '#81B29A' }, hasRings: true, starColor: '#F4F1DE', starRadius: 0.81 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 63,
    designation: 'TESSERACT-V',
    archetype: 'Non-Euclidean Fold',
    orbitalRadiusAU: 0.95,
    surfaceTempKelvin: 290,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 77.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.0, surfacePressureAtm: 1.00 },
    topography: { description: 'Folded landscapes where horizons abruptly curve upward at 90-degree right angles.', surfaceWaterCoverage: 50, elevationVarianceMeters: 1000 },
    civilization: { tier: 'Tier 3', status: '4-Dimensional Spatial Manifold', kardashevIndex: 2.10 },
    anomalyCoordinates: [0.00, 1.00],
    anomalyDescription: 'Navigating into the north pole repositions the craft at the south pole with inverted velocity.',
    visuals: { palette: { primaryColor: '#00F5D4', secondaryColor: '#7B2CBF', atmosphereColor: '#F72585' }, hasRings: true, starColor: '#FFFFFF', starRadius: 1.00 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 64,
    designation: 'SHADOW-VAULT',
    archetype: 'Carbon Nanotube Sink',
    orbitalRadiusAU: 1.75,
    surfaceTempKelvin: 160,
    atmosphere: { primaryGas: 'Methane', primaryPercentage: 90.0, secondaryGas: 'Argon', secondaryPercentage: 10.0, surfacePressureAtm: 0.02 },
    topography: { description: 'Forests of carbon nanotubes absorbing 99.96% of all visible light and radar signals.', surfaceWaterCoverage: 0, elevationVarianceMeters: 3100 },
    civilization: { tier: 'Tier 0', status: 'Photonic Black Hole Equivalent', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.29, -0.66],
    anomalyDescription: 'Visual sensors show pitch black; detected only by sudden background star cluster occlusion.',
    visuals: { palette: { primaryColor: '#03071E', secondaryColor: '#000000', atmosphereColor: '#0F0F0F' }, hasRings: false, starColor: '#E0E7FF', starRadius: 0.87 },
    isCaptured: false,
    isDiscovered: false,
  },

  // =========================================================================
  // SECTOR 6: STRANGE FLORA & ELEMENTAL BIOMES (#65 – #75)
  // =========================================================================
  {
    catalogIndex: 65,
    designation: 'MYCELIUM-MAX',
    archetype: 'Mega-Fungal',
    orbitalRadiusAU: 1.18,
    surfaceTempKelvin: 292,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 72.0, secondaryGas: 'Oxygen', secondaryPercentage: 19.0, surfacePressureAtm: 1.20 },
    topography: { description: 'Gigantic shelf mushroom caps spanning 15 km wide anchored to colossal fungal stalks.', surfaceWaterCoverage: 38, elevationVarianceMeters: 5400 },
    civilization: { tier: 'Tier 0', status: 'Planetary Super-Organism Fungi', kardashevIndex: 0.12 },
    anomalyCoordinates: [0.44, 0.51],
    anomalyDescription: 'Spore storms release dielectric organic dust, grounding communications antennae.',
    visuals: { palette: { primaryColor: '#9C6644', secondaryColor: '#7F5539', atmosphereColor: '#DDB892' }, hasRings: false, starColor: '#FFE5D9', starRadius: 1.04 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 66,
    designation: 'CHLOROPHYLL-X',
    archetype: 'Hyper-Floral',
    orbitalRadiusAU: 0.98,
    surfaceTempKelvin: 302,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 62.0, secondaryGas: 'Oxygen', secondaryPercentage: 35.0, surfacePressureAtm: 1.30 },
    topography: { description: 'Carnivorous jungle canopy covering 90% of the crust; branches snap shut like jaws.', surfaceWaterCoverage: 45, elevationVarianceMeters: 4200 },
    civilization: { tier: 'Tier 0', status: 'Predatory Floral Ecosystem', kardashevIndex: 0.06 },
    anomalyCoordinates: [-0.62, -0.18],
    anomalyDescription: 'Giant sun-tracking leaves swivel toward thruster heat trails, reflecting radar into green scatter.',
    visuals: { palette: { primaryColor: '#2D6A4F', secondaryColor: '#1B4332', atmosphereColor: '#74C69D' }, hasRings: false, starColor: '#FFF1BD', starRadius: 1.01 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 67,
    designation: 'PETRO-BLOOM',
    archetype: 'Hydrocarbon Sludge',
    orbitalRadiusAU: 1.35,
    surfaceTempKelvin: 310,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 80.0, secondaryGas: 'Methane', secondaryPercentage: 12.0, surfacePressureAtm: 1.40 },
    topography: { description: 'Black crude-oil oceans dotted with islands of solid paraffin wax and tar springs.', surfaceWaterCoverage: 0, elevationVarianceMeters: 1100 },
    civilization: { tier: 'Tier 0', status: 'Hydrocarbon Pre-Life Biome', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.31, -0.83],
    anomalyDescription: 'Heavy petroleum rainfall creates an optical film over sensors, causing severe refraction.',
    visuals: { palette: { primaryColor: '#1C1917', secondaryColor: '#44403C', atmosphereColor: '#CA8A04' }, hasRings: false, starColor: '#FED7AA', starRadius: 0.96 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 68,
    designation: 'KELP-SUBLIME',
    archetype: 'Pelagic Forest',
    orbitalRadiusAU: 1.05,
    surfaceTempKelvin: 286,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 78.0, secondaryGas: 'Oxygen', secondaryPercentage: 21.0, surfacePressureAtm: 1.02 },
    topography: { description: '100% ocean surface filled with massive kelp whose gas bladders form floating islands.', surfaceWaterCoverage: 99.8, elevationVarianceMeters: 300 },
    civilization: { tier: 'Tier 0', status: 'Oceanic Plant Colossus', kardashevIndex: 0.02 },
    anomalyCoordinates: [-0.48, 0.39],
    anomalyDescription: 'Bioluminescent gas bulbs pulsing in cadence mimic runway approach lights on radar displays.',
    visuals: { palette: { primaryColor: '#0F4C5C', secondaryColor: '#E36414', atmosphereColor: '#5F9EA0' }, hasRings: false, starColor: '#FFFDF0', starRadius: 1.00 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 69,
    designation: 'AMBER-FOLIAGE',
    archetype: 'Glass Forest',
    orbitalRadiusAU: 1.10,
    surfaceTempKelvin: 278,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 82.0, secondaryGas: 'Oxygen', secondaryPercentage: 17.0, surfacePressureAtm: 0.88 },
    topography: { description: 'Forests where tree trunks, branches, and needles are composed of pure brittle silicate glass.', surfaceWaterCoverage: 22, elevationVarianceMeters: 3700 },
    civilization: { tier: 'Tier 0', status: 'Crystalline Plant Biome', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.57, -0.25],
    anomalyDescription: 'Winds striking glass leaves generate chiming frequencies across UHF communication lines.',
    visuals: { palette: { primaryColor: '#D4A373', secondaryColor: '#CCD5AE', atmosphereColor: '#FAEDCD' }, hasRings: false, starColor: '#FFF2B2', starRadius: 1.02 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 70,
    designation: 'BIOLUME-BAY',
    archetype: 'Phosphorescent Ocean',
    orbitalRadiusAU: 1.14,
    surfaceTempKelvin: 291,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 76.0, secondaryGas: 'Oxygen', secondaryPercentage: 22.0, surfacePressureAtm: 1.05 },
    topography: { description: 'Warm turquoise oceans filled with trillions of glowing cyan dinoflagellates along white coral shores.', surfaceWaterCoverage: 74, elevationVarianceMeters: 2100 },
    civilization: { tier: 'Tier 0', status: 'Glowing Bacterial Sea', kardashevIndex: 0.01 },
    anomalyCoordinates: [-0.17, -0.71],
    anomalyDescription: 'Night side glows brighter than day side; optical feed washes out in chemical bioluminescence.',
    visuals: { palette: { primaryColor: '#00F5D4', secondaryColor: '#01BAEF', atmosphereColor: '#0B4F6C' }, hasRings: false, starColor: '#FDFCDC', starRadius: 1.03 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 71,
    designation: 'SPORE-TUNDRA',
    archetype: 'Cryo-Fungal',
    orbitalRadiusAU: 1.62,
    surfaceTempKelvin: 228,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 85.0, secondaryGas: 'Carbon Dioxide', secondaryPercentage: 10.0, surfacePressureAtm: 0.75 },
    topography: { description: 'Frozen permafrost plains with hard-shelled cryogenic fungal bulbs waiting for heat.', surfaceWaterCoverage: 12, elevationVarianceMeters: 1800 },
    civilization: { tier: 'Tier 0', status: 'Cryogenic Fungal Reservoir', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.68, 0.44],
    anomalyDescription: 'Engine exhaust triggers instant spore release geysers below, showering upper clouds in dust.',
    visuals: { palette: { primaryColor: '#588157', secondaryColor: '#3A5A40', atmosphereColor: '#A3B18A' }, hasRings: false, starColor: '#E9ECEF', starRadius: 0.86 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 72,
    designation: 'IRON-BARK',
    archetype: 'Metallophyte Forest',
    orbitalRadiusAU: 0.89,
    surfaceTempKelvin: 320,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 74.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 1.15 },
    topography: { description: 'Trees concentrating hematite from soil, growing solid metallic trunks and razor iron leaves.', surfaceWaterCoverage: 31, elevationVarianceMeters: 4900 },
    civilization: { tier: 'Tier 0', status: 'Metallic Floral Forest', kardashevIndex: 0.00 },
    anomalyCoordinates: [-0.82, 0.16],
    anomalyDescription: 'Metal forest canopy acts as an antenna shield, blocking ground-penetrating radar pulses.',
    visuals: { palette: { primaryColor: '#780000', secondaryColor: '#003049', atmosphereColor: '#C1121F' }, hasRings: true, starColor: '#FF9E00', starRadius: 1.12 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 73,
    designation: 'CORAL-DRY',
    archetype: 'Uplifted Ancient Reef',
    orbitalRadiusAU: 1.28,
    surfaceTempKelvin: 282,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 79.0, secondaryGas: 'Oxygen', secondaryPercentage: 20.0, surfacePressureAtm: 0.90 },
    topography: { description: 'Evaporated sea leaving 2-km-high petrified coral walls and calcium arches exposed to dry air.', surfaceWaterCoverage: 3, elevationVarianceMeters: 3400 },
    civilization: { tier: 'Tier 0', status: 'Dry Coral Ruins', kardashevIndex: 0.00 },
    anomalyCoordinates: [0.24, 0.67],
    anomalyDescription: 'Winds through porous coral produce acoustic flute harmonics that disrupt acoustic filters.',
    visuals: { palette: { primaryColor: '#F4A261', secondaryColor: '#E76F51', atmosphereColor: '#2A9D8F' }, hasRings: false, starColor: '#FFF6E5', starRadius: 0.97 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 74,
    designation: 'CARNIVORA-9',
    archetype: 'Trapdoor Floral',
    orbitalRadiusAU: 1.06,
    surfaceTempKelvin: 298,
    atmosphere: { primaryGas: 'Nitrogen', primaryPercentage: 70.0, secondaryGas: 'Oxygen', secondaryPercentage: 22.0, surfacePressureAtm: 1.12 },
    topography: { description: 'Deep craters formed by pitcher plants up to 500 meters wide with bubbling enzymatic acid.', surfaceWaterCoverage: 42, elevationVarianceMeters: 3100 },
    civilization: { tier: 'Tier 0', status: 'Macro-Trapdoor Biome', kardashevIndex: 0.01 },
    anomalyCoordinates: [-0.38, -0.54],
    anomalyDescription: 'Hourly digestive geysers launch organic droplets into orbit, triggering collision alarms.',
    visuals: { palette: { primaryColor: '#550C18', secondaryColor: '#780116', atmosphereColor: '#F77F00' }, hasRings: false, starColor: '#FFFBE6', starRadius: 1.00 },
    isCaptured: false,
    isDiscovered: false,
  },
  {
    catalogIndex: 75,
    designation: 'DOOMSNEXUS',
    archetype: 'Human-Engineered Singularity Hub',
    orbitalRadiusAU: 1.02,
    surfaceTempKelvin: 288,
    atmosphere: {
      primaryGas: 'Nitrogen',
      primaryPercentage: 78.0,
      secondaryGas: 'Oxygen',
      secondaryPercentage: 21.0,
      surfacePressureAtm: 1.00,
      traceGases: 'Synthesized Carbon-Chrono Byproducts',
    },
    topography: {
      description: 'Gargantuan artificial lattice constructed by human hands. Appears as a peaceful blue-green terrestrial sphere until deep telemetry disturbs the core.',
      surfaceWaterCoverage: 55,
      elevationVarianceMeters: 4500,
      primaryBiome: 'Synthetic Server Spire',
    },
    civilization: {
      tier: 'Tier Omega',
      status: 'HUMAN CREATION // DORMANT RECURSIVE ARCHIVE',
      kardashevIndex: 3.5,
      structureType: 'Synthetic Singularity Cradle',
    },
    anomalyCoordinates: [0.00, 0.00],
    anomalyDescription: 'Archival core dormant. Human biometric signature detected. Deep-spectrum scan will awaken synthetic singularity defenses.',
    visuals: {
      palette: {
        primaryColor: '#1d4ed8', // Starts calm oceanic blue
        secondaryColor: '#1e293b',
        atmosphereColor: '#60a5fa', // Soft cyan/blue atmosphere
        glowColor: '#38bdf8',
      },
      hasRings: true,
      starColor: '#ffffff',
      starRadius: 1.0,
      roughness: 0.4,
    },
    isCaptured: false,
    isDiscovered: false,
    isMalluvalyTarget: false,
  },
];

export function getPlanetDossier(identifier: number | string): PlanetDossier | undefined {
  if (typeof identifier === 'number') {
    return planetCatalog.find((p) => p.catalogIndex === identifier) || planetCatalog[0];
  }
  return planetCatalog.find((p) => p.designation.toLowerCase() === identifier.toLowerCase());
}

export function getAllPlanets(): PlanetDossier[] {
  return planetCatalog;
}

export default planetCatalog;